spring.application.name=banking-backend

spring.profiles.active=prod

spring.jackson.default-property-inclusion=non_null

server.port=8000

app.name=Temi Bank

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbs.bind=TRACE

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
app.mail.from=${SPRING_MAIL_USERNAME}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true