spring.application.name=banking-backend

spring.profiles.active=dev

spring.jackson.default-property-inclusion=non_null

server.port=8000

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbs.bind=TRACE

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}